# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('project_type', models.CharField(choices=[('P', 'Product'), ('C', 'Consult')], max_length=1)),
                ('owner', models.IntegerField()),
                ('update_date', models.DateField()),
                ('create_date', models.DateField()),
            ],
        ),
    ]
